repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
        args: ['--maxkb=50000']

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Format imports
        args:
        - --line-length=310

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Format code
        args: # arguments to configure black
          - --line-length=130

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        args: [--line-length=310]
        additional_dependencies: [black==21.12b0]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --ignore=E203,W503
          - --max-line-length=310
        name: Check PEP8
