version: '3.7'

services:
  memgraph:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 7687:7687
      - 7444:7444
      - 3000:3000
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    environment:
      - MG_AUTH_ENABLED=false
      - MG_LISTEN_ADDRESS=localhost
      - MG_LISTEN_PORT=7687
      - MG_LOG_LEVEL=info
    networks:
      - default
    entrypoint: ["/usr/bin/supervisord"]


  # backend:
  #   build: ./backend
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - memgraph
  #   networks:
  #     - default

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend
  #   networks:
  #     - default

networks:
  default:
    name: memgraph

volumes:
  mg_lib:
  mg_log:
  mg_etc:
